### ISSUE TITLE
Requested keys of a value that is not an object

### ISSUE THREAD

**Issue by satvikmaker** [bozzmob/React-Native-Alphabetical-ListView#1]
Requested keys of a value that is not an object.

```
this.totalHeight = Object.keys(data)
```

Here the value of data is `undefined`. Error is pointed at this [line](https://github.com/bozzmob/React-Native-Alphabetical-ListView/blob/master/components/SelectableSectionsListView.js#L72)
#### Code-

```
 calculateTotalHeight(data) {
    data = data || this.props.data;

    if (Array.isArray(data)) {
      return;
    }

    this.sectionItemCount = {};
    console.log("data="+data);
    console.log("data="+JSON.stringify(data));
    this.totalHeight = Object.keys(data)
      .reduce((carry, key) => {
        var itemCount = data[key].length;
        carry += itemCount * this.props.cellHeight;
        carry += this.props.sectionHeaderHeight;

        this.sectionItemCount[key] = itemCount;

        return carry;
      }, 0);
  }
```

> In `calculateTotalHeight(data)` the `data`is as undefined.
#### Screenshot-

![screenshot_2015-12-28-16-06-35](https://cloud.githubusercontent.com/assets/1252941/12017487/4baa6268-ad7d-11e5-8538-426395c5c8c3.png)

**Comment by johanneslumpe** [comment]
Are you passing in `data` via props?

**Comment by satvikmaker** [comment]
No, I don't think I am passing any data. I think that's the problem.

This is the file in the repo.

This is the code-

```
'use strict';
var React = require('react-native');
var {AppRegistry} = React;

var reactnativeAlphabeticalListView = require('./components/SelectableSectionsListView');

AppRegistry.registerComponent('reactnativeAlphabeticalListView', () => reactnativeAlphabeticalListView);
```

Please can you guide me on the JSON structure?

**Comment by niharikaneeraj** [comment]
hey this is great app. great work @johanneslumpe . really appreciate your work. and tnx @bozzmob for compiling it. hope this kicks-off well.

**Comment by manoj42kumar24** [comment]
Happy to see @johanneslumpe :) +1 for this repo. Thanks both of you.

**Comment by satvikmaker** [comment]
Fixed issue with latest commit.

**Comment by sam26880** [comment]
@bozzmob any update on this? I'm trying to use this but it breaks on this line # 38 of SectionList.js

`UIManager.measureViewsInRect(rect, e.target, noop, (frames) => {`

**Comment by satvikmaker** [comment]
@sam26880 Yes. It was fixed as a part of earlier commit. Just pass proper `data` as props. It should work.

**Comment by sam26880** [comment]
@bozzmob Not sure I understand. I do have the latest commit. Do you have an example I can take a look at? I basically downloaded the code 2 days ago so I'm assuming I have the latest code.

**Comment by satvikmaker** [comment]
Hi, I am sorry I was AFK. @sam26880 . Please use the current code base. And build it. What I have is a n example project itself. I have used the library to develop the working project. The project has to work :)
