### ISSUE TITLE
Plan for Release v0.2

### ISSUE THREAD

**Issue by satvikmaker** [bozzmob/React-Native-Alphabetical-ListView#2]
Plan for the Release v0.2
- [x]  Fixing #1 
- [x]  Making the Alphabetical ListView to work

**Comment by johanneslumpe** [comment]
@bozzmob have you seen https://github.com/sunnylqm/react-native-alphabetlistview ?

**Comment by satvikmaker** [comment]
Thanks for the reference. I will have a look at it. :)

**Comment by satvikmaker** [comment]
Code Complete. Released.
